//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagementFramework.RegistrationMQService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RegistrationMQService.IRegistrationServiceMQ")]
    public interface IRegistrationServiceMQ {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRegistrationServiceMQ/RegisterUser")]
        void RegisterUser(ProjectManagementFramework.RegistrationMQService.RegisterUser request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRegistrationServiceMQ/RegisterUser")]
        System.Threading.Tasks.Task RegisterUserAsync(ProjectManagementFramework.RegistrationMQService.RegisterUser request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegisterUser", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RegisterUser {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Model.NewUser newUser;
        
        public RegisterUser() {
        }
        
        public RegisterUser(Model.NewUser newUser) {
            this.newUser = newUser;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRegistrationServiceMQChannel : ProjectManagementFramework.RegistrationMQService.IRegistrationServiceMQ, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegistrationServiceMQClient : System.ServiceModel.ClientBase<ProjectManagementFramework.RegistrationMQService.IRegistrationServiceMQ>, ProjectManagementFramework.RegistrationMQService.IRegistrationServiceMQ {
        
        public RegistrationServiceMQClient() {
        }
        
        public RegistrationServiceMQClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegistrationServiceMQClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistrationServiceMQClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistrationServiceMQClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void RegisterUser(ProjectManagementFramework.RegistrationMQService.RegisterUser request) {
            base.Channel.RegisterUser(request);
        }
        
        public System.Threading.Tasks.Task RegisterUserAsync(ProjectManagementFramework.RegistrationMQService.RegisterUser request) {
            return base.Channel.RegisterUserAsync(request);
        }
    }
}
